/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        // Plan & Design Token Primary Palette
        'surface-base':    '#282E16',
        'surface-deep':    '#1D230E',
        'surface-card':    '#30371A',
        'surface-raised':  '#38411F',
        'surface-highest': '#485327',
        'text-primary':    '#F0F3E8',
        'text-secondary':  '#D8DFC8',
        'text-muted':      '#AAB596',
        'text-accent':     '#C2CE9F',
        'accent-primary':  '#A4B566',
        'accent-container':'#8B9B4C',
        'accent-dim':      '#6B7D3B',
        'border-default':  '#525E31',
        'border-accent':   '#5D6A37',
        'border-subtle':   '#454F26',
        'status-healthy':  '#A4B566',
        'status-monitor':  '#D99B26',
        'status-danger':   '#E57373',

        // Direct compatibility aliases matching DESIGN/ boards
        "forest-base": "#282E16",
        "forest-deep": "#1D230E",
        "forest-card": "#30371A",
        "forest-raised": "#38411F",
        "lime-leaf": "#6B7D3B",
        "sage-muted": "#AAB596",
        "sage-cream": "#F0F3E8",
        "hairline-emerald": "#525E31",

        // Material/Design Token names used in code.html
        "surface": "#282E16",
        "surface-variant": "#30371A",
        "surface-container-lowest": "#161B09",
        "surface-container-low": "#212711",
        "surface-container": "#353D1E",
        "surface-container-high": "#3F4922",
        "surface-container-highest": "#485327",
        "surface-dim": "#1E240D",
        "on-surface": "#F0F3E8",
        "on-surface-variant": "#D8DFC8",
        "outline": "#5D6A37",
        "outline-variant": "#454F26",
        "primary": "#A4B566",
        "on-primary": "#1F240F",
        "primary-container": "#8B9B4C",
        "on-primary-container": "#1F240F",
        "primary-fixed": "#D2DCB4",
        "primary-fixed-dim": "#9EAF6D",
        "secondary": "#C2CE9F",
        "on-secondary": "#1F240F",
        "secondary-container": "#3A4320",
        "on-secondary-container": "#E1E8D1",
        "secondary-fixed": "#D2DCB4",
        "secondary-fixed-dim": "#c2caaa",
        "tertiary": "#C2CE9F",
        "on-tertiary": "#2e3129",
        "tertiary-container": "#8B9B4C",
        "on-tertiary-container": "#1F240F",
        "error": "#E57373",
        "on-error": "#690005",
        "error-container": "#93000a",
        "on-error-container": "#ffdad6",
      },
      spacing: {
        'space-xs': '0.25rem',
        'space-sm': '0.5rem',
        'space-md': '0.75rem',
        'space-lg': '1.25rem',
        'space-xl': '2rem',
        'space-2xl': '2.5rem',
        'margin-mobile': '0.75rem',
        'margin-desktop': '2rem',
      },
      fontFamily: {
        'display': ['Chivo', 'sans-serif'],
        'body':    ['Chivo', 'sans-serif'],
        'mono':    ['JetBrains Mono', 'monospace'],
        'headline-lg': ['Chivo', 'sans-serif'],
        'headline-md': ['Chivo', 'sans-serif'],
        'headline-sm': ['Chivo', 'sans-serif'],
        'body-lg': ['Chivo', 'sans-serif'],
        'body-md': ['Chivo', 'sans-serif'],
        'body-sm': ['Chivo', 'sans-serif'],
        'label-lg': ['JetBrains Mono', 'monospace'],
        'label-md': ['JetBrains Mono', 'monospace'],
        'label-sm': ['JetBrains Mono', 'monospace'],
        'data-metric': ['Chivo', 'sans-serif'],
      },
      fontSize: {
        'headline-lg': ['28px', { lineHeight: '34px', letterSpacing: '-0.01em', fontWeight: '700' }],
        'headline-md': ['22px', { lineHeight: '28px', fontWeight: '600' }],
        'headline-sm': ['18px', { lineHeight: '24px', fontWeight: '600' }],
        'body-lg': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'body-md': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'body-sm': ['12px', { lineHeight: '16px', fontWeight: '400' }],
        'label-lg': ['14px', { lineHeight: '18px', letterSpacing: '0.06em', fontWeight: '600' }],
        'label-md': ['12px', { lineHeight: '16px', letterSpacing: '0.08em', fontWeight: '500' }],
        'label-sm': ['10px', { lineHeight: '14px', letterSpacing: '0.1em', fontWeight: '500' }],
        'data-metric': ['36px', { lineHeight: '40px', fontWeight: '800', letterSpacing: '-0.02em' }],
      },
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
  ],
}
