import React from 'react';
import {
  Plus,
  BellPlus,
  Camera,
  PlusCircle,
  CalendarPlus,
  ClipboardCheck,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  CheckSquare,
  Calendar,
  XCircle,
  Check,
  CheckCircle2,
  ChevronRight,
  ChevronDown,
  ChevronUp,
  X,
  LayoutDashboard,
  Trash2,
  PieChart,
  Download,
  Leaf,
  Pencil,
  AlertCircle,
  CalendarCheck,
  Repeat,
  Heart,
  SwitchCamera,
  Trees,
  Grid,
  Ruler,
  MapPin,
  Lock,
  LogIn,
  LogOut,
  UserCog,
  Map,
  Activity,
  Crosshair,
  Bell,
  BellRing,
  BellOff,
  User,
  UserPlus,
  Users,
  Image,
  Hash,
  Printer,
  Loader2,
  Globe,
  QrCode,
  ScanLine,
  TrendingUp,
  Radio,
  RotateCw,
  Minus,
  Save,
  GraduationCap,
  Search,
  Send,
  ShieldCheck,
  Sliders,
  Upload,
  UploadCloud,
  CheckCheck,
  Eye,
  AlertTriangle,
  Droplets,
  HelpCircle,
  IdCard,
  History,
  Info,
  Circle,
  LineChart,
  RefreshCw,
  Flashlight,
  FlashlightOff,
  UserCheck,
  ZoomIn,
} from 'lucide-react';

const ICON_MAP = {
  add: Plus,
  add_alert: BellPlus,
  add_a_photo: Camera,
  add_circle: PlusCircle,
  add_task: CalendarPlus,
  alarm_add: BellPlus,
  app_registration: ClipboardCheck,
  arrow_back: ArrowLeft,
  arrow_forward: ArrowRight,
  arrow_upward: ArrowUp,
  arrow_upward_alt: ArrowUp,
  arrow_drop_down: ChevronDown,
  assignment_turned_in: CheckSquare,
  badge: IdCard,
  calendar_month: Calendar,
  calendar_today: Calendar,
  cancel: XCircle,
  check: Check,
  check_circle: CheckCircle2,
  chevron_right: ChevronRight,
  chevron_down: ChevronDown,
  chevron_up: ChevronUp,
  circle: Circle,
  cloud_upload: UploadCloud,
  close: X,
  dashboard: LayoutDashboard,
  grid_view: LayoutDashboard,
  delete: Trash2,
  donut_large: PieChart,
  download: Download,
  download_for_offline: Download,
  eco: Leaf,
  edit: Pencil,
  energy_savings_leaf: Leaf,
  error: AlertCircle,
  event_available: CalendarCheck,
  event_note: Calendar,
  event_repeat: Repeat,
  expand_more: ChevronDown,
  expand_less: ChevronUp,
  fact_check: CheckSquare,
  favorite: Heart,
  flashlight_on: Flashlight,
  flashlight_off: FlashlightOff,
  flip_camera_ios: SwitchCamera,
  forest: Trees,
  grid_4x4: Grid,
  groups: Users,
  height: Ruler,
  history_toggle_off: History,
  id_card: IdCard,
  info: Info,
  install_mobile: Download,
  location_on: MapPin,
  lock: Lock,
  login: LogIn,
  logout: LogOut,
  manage_accounts: UserCog,
  map: Map,
  military_tech: ShieldCheck,
  monitoring: Activity,
  my_location: Crosshair,
  notifications: Bell,
  notifications_active: BellRing,
  notifications_paused: BellOff,
  officer: ShieldCheck,
  park: Trees,
  person: User,
  person_add: UserPlus,
  person_search: UserCheck,
  photo_camera: Camera,
  photo_library: Image,
  pin: Hash,
  pin_drop: MapPin,
  print: Printer,
  progress_activity: Loader2,
  public: Globe,
  qr_code: QrCode,
  qr_code_2: QrCode,
  qr_code_scanner: ScanLine,
  query_stats: TrendingUp,
  radar: Radio,
  radio_button_checked: CheckCircle2,
  radio_button_unchecked: Circle,
  refresh: RotateCw,
  remove: Minus,
  save: Save,
  school: GraduationCap,
  search: Search,
  send: Send,
  shield: ShieldCheck,
  shield_person: ShieldCheck,
  ssid_chart: LineChart,
  straighten: Ruler,
  sync: RefreshCw,
  timeline: TrendingUp,
  tune: Sliders,
  upload: Upload,
  upload_file: Upload,
  verified: CheckCheck,
  visibility: Eye,
  vital_signs: Activity,
  warning: AlertTriangle,
  water_drop: Droplets,
  zoom_in: ZoomIn,
};

/**
 * Universal Tailwind-styled Icon component.
 * 100% offline self-hosted, tree-shaken Lucide React SVG components for instant zero-network rendering.
 */
export default function Icon({
  name,
  className = '',
  size,
  strokeWidth = 2,
  ...props
}) {
  if (!name) return null;

  const normalized = String(name).trim().toLowerCase();
  const Component = ICON_MAP[normalized] || HelpCircle;

  const hasExplicitWidth = /\bw-/.test(className);
  const sizeClass = hasExplicitWidth || size ? '' : 'w-[1em] h-[1em]';

  return (
    <Component
      className={`inline-block shrink-0 ${sizeClass} ${className}`.trim()}
      size={size || (hasExplicitWidth ? undefined : 20)}
      strokeWidth={strokeWidth}
      {...props}
    />
  );
}
