import React from 'react';
import {
  Plus,
  BellPlus,
  Camera,
  PlusCircle,
  CalendarPlus,
  ClipboardCheck,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  CheckSquare,
  Calendar,
  XCircle,
  Check,
  CheckCircle2,
  ChevronRight,
  ChevronDown,
  X,
  LayoutDashboard,
  Trash2,
  PieChart,
  Download,
  Leaf,
  Pencil,
  AlertCircle,
  CalendarCheck,
  Repeat,
  Heart,
  SwitchCamera,
  Trees,
  Grid,
  Ruler,
  MapPin,
  Lock,
  LogIn,
  LogOut,
  UserCog,
  Map,
  Activity,
  Crosshair,
  Bell,
  User,
  UserPlus,
  Image,
  Hash,
  Printer,
  Loader2,
  Globe,
  QrCode,
  ScanLine,
  TrendingUp,
  Radio,
  RotateCw,
  Minus,
  Save,
  GraduationCap,
  Search,
  Send,
  ShieldCheck,
  Sliders,
  Upload,
  CheckCheck,
  Eye,
  AlertTriangle,
  Droplets,
  HelpCircle,
} from 'lucide-react';

const ICON_MAP = {
  add: Plus,
  add_alert: BellPlus,
  add_a_photo: Camera,
  add_circle: PlusCircle,
  add_task: CalendarPlus,
  alarm_add: BellPlus,
  app_registration: ClipboardCheck,
  arrow_back: ArrowLeft,
  arrow_forward: ArrowRight,
  arrow_upward: ArrowUp,
  assignment_turned_in: CheckSquare,
  calendar_month: Calendar,
  cancel: XCircle,
  check: Check,
  check_circle: CheckCircle2,
  chevron_right: ChevronRight,
  chevron_down: ChevronDown,
  close: X,
  dashboard: LayoutDashboard,
  grid_view: LayoutDashboard,
  delete: Trash2,
  donut_large: PieChart,
  download: Download,
  eco: Leaf,
  edit: Pencil,
  energy_savings_leaf: Leaf,
  error: AlertCircle,
  event_available: CalendarCheck,
  event_repeat: Repeat,
  favorite: Heart,
  flip_camera_ios: SwitchCamera,
  forest: Trees,
  grid_4x4: Grid,
  height: Ruler,
  install_mobile: Download,
  location_on: MapPin,
  lock: Lock,
  login: LogIn,
  logout: LogOut,
  manage_accounts: UserCog,
  map: Map,
  monitoring: Activity,
  my_location: Crosshair,
  notifications: Bell,
  park: Trees,
  person: User,
  person_add: UserPlus,
  photo_camera: Camera,
  photo_library: Image,
  pin: Hash,
  pin_drop: MapPin,
  print: Printer,
  progress_activity: Loader2,
  public: Globe,
  qr_code: QrCode,
  qr_code_scanner: ScanLine,
  query_stats: TrendingUp,
  radar: Radio,
  refresh: RotateCw,
  remove: Minus,
  save: Save,
  school: GraduationCap,
  search: Search,
  send: Send,
  shield_person: ShieldCheck,
  straighten: Ruler,
  tune: Sliders,
  upload: Upload,
  upload_file: Upload,
  verified: CheckCheck,
  visibility: Eye,
  warning: AlertTriangle,
  water_drop: Droplets,
};

/**
 * Universal Tailwind-styled Icon component.
 * Explicitly tree-shaken Lucide React SVG components for instant rendering, zero network lag, and minimal bundle footprint.
 */
export default function Icon({
  name,
  className = 'w-5 h-5',
  size,
  strokeWidth = 2,
  ...props
}) {
  if (!name) return null;

  const normalized = String(name).trim().toLowerCase();
  const Component = ICON_MAP[normalized] || HelpCircle;

  return (
    <Component
      className={`inline-block shrink-0 ${className}`}
      size={size}
      strokeWidth={strokeWidth}
      {...props}
    />
  );
}
